### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by drprajapati** [ShenYujun/InterFaceGAN#32]
(base) PS E:\darshan\pytorch_stylegan_encoder-master\InterFaceGAN> python generate_data.py -m stylegan_ffhq -o data/pggan_celebahq -n 10000
[2020-01-20 03:53:48,282][INFO] Initializing generator.
[2020-01-20 03:53:48,521][WARNING] No pre-trained model will be loaded!
Traceback (most recent call last):
  File "generate_data.py", line 111, in <module>
    main()
  File "generate_data.py", line 64, in main
    model = StyleGANGenerator(args.model_name, logger)
  File "E:\darshan\pytorch_stylegan_encoder-master\InterFaceGAN\models\stylegan_generator.py", line 42, in __init__
    super().__init__(model_name, logger)
  File "E:\darshan\pytorch_stylegan_encoder-master\InterFaceGAN\models\base_generator.py", line 103, in __init__
    self.model.eval().to(self.run_device)
  File "C:\Users\HpZ8\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 426, in to
    return self._apply(convert)
  File "C:\Users\HpZ8\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\HpZ8\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\HpZ8\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\HpZ8\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 224, in _apply
    param_applied = fn(param)
  File "C:\Users\HpZ8\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 424, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "C:\Users\HpZ8\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 192, in _lazy_init
    _check_driver()
  File "C:\Users\HpZ8\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 95, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by sandhyalaxmiK** [comment]
Have downloaded stylegan_ffhq model (karras2019stylegan-ffhq-1024x1024.pkl ) from stylegan github and placed in models/pretrain folder ??

**Comment by drprajapati** [comment]
Thank you for your reply...Yes that error is solved...!!

**Comment by drprajapati** [comment]
Can i train this on my own image dataset ??

**Comment by sandhyalaxmiK** [comment]
First you train your image dataset with stylegan model, get pre-trained weights of your model, and keep this pretrained model in models/pretrain directory. and then do training...

**Comment by drprajapati** [comment]
Okay ma'am... Thank you ma'am...
I tried several stylegan repository but i got error... Do you know about the ideal stylegan code ?

**Comment by sandhyalaxmiK** [comment]
https://github.com/NVlabs/stylegan This is the official repository which i am using.

**Comment by drprajapati** [comment]
Thank you so much ma'am...👏
